"""IASTAM P7 demo dashboard: one image through B0-B4, live on CPU, or from static fallback assets.

    python -m pip install -r demo/requirements-dashboard.txt
    streamlit run demo/dashboard.py

Sections: A overview, B image input, C detection (plain YOLO vs SAHI), D semantic packet,
E experiment (B0-B4, direct / relay), F communication simulation, G results, H export.

Live mode runs demo/demo_pipeline.py: the sat7 stages the committed results were produced with, on
the bundled ONNX model, no GPU, no torch, no dataset. If the live pipeline cannot run (a missing
package, missing weights) the page says what is missing and how to fix it, and shows
demo/fallback_assets/ (pre-generated by demo/make_fallback_assets.py) in the same interface.

No number is typed into this file. Canonical results are read from code/results at run time
(demo/demo_data.py) and keep their repo labels; everything computed on the image in front of you
is labelled with what it is: bytes MEASURED, times MEASURED on this machine, link SIM, energy
ESTIMATE, and SYNTH whenever the image is one of the bundled synthetic stand-ins.
"""
from __future__ import annotations

import base64
import json
import os
import sys
import traceback
from pathlib import Path

import altair as alt
import pandas as pd
import streamlit as st

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import demo_data as D  # noqa: E402  (standard library only: always importable)

try:                                    # the live pipeline: OpenCV, onnxruntime, sat7
    import demo_pipeline as P  # noqa: E402
    LIVE_IMPORT_ERROR = None
except Exception as _e:                 # noqa: BLE001  any import failure -> static fallback
    P = None
    LIVE_IMPORT_ERROR = f"{type(_e).__name__}: {_e}"

if os.environ.get("P7_DEMO_FORCE_FALLBACK"):     # rehearse the no-pipeline case on a working machine
    P, LIVE_IMPORT_ERROR = None, "live pipeline switched off by P7_DEMO_FORCE_FALLBACK (rehearsal)"

BLUE, ORANGE, AQUA, YELLOW = "#2a78d6", "#eb6834", "#1baf7a", "#eda100"
SWATH_KEY = "swath"

st.set_page_config(page_title="IASTAM P7 — semantic downlink demo", layout="wide")


# ====================================================================================== helpers
def guard(fn, *args):
    """Run one section; a failure becomes a readable message, never a blank page."""
    try:
        fn(*args)
    except Exception as e:  # noqa: BLE001
        st.error(f"This section could not be rendered: {type(e).__name__}: {e}")
        with st.expander("Technical details"):
            st.code(traceback.format_exc())


def fmt_bytes(n) -> str:
    if n is None:
        return "—"
    n = float(n)
    return f"{n / 1e6:,.2f} MB" if n >= 1e6 else f"{n / 1e3:,.1f} kB" if n >= 1e4 else f"{n:,.0f} B"


def fmt_time(s) -> str:
    if s is None:
        return "—"
    return f"{s / 3600:,.2f} h" if s >= 3600 else f"{s:,.1f} s" if s >= 1 else f"{1e3 * s:,.2f} ms"


def fmt_energy(j) -> str:
    if j is None:
        return "—"
    return f"{j / 1e3:,.2f} kJ" if j >= 1e3 else f"{j:,.2f} J" if j >= 0.01 else f"{1e3 * j:,.2f} mJ"


def bars(df: pd.DataFrame, x: str, y: str, colour: str | None = None, log: bool = False,
         y_title: str | None = None, stack: bool = False, height: int = 280):
    """One-axis bar chart with hover values; `colour` names a categorical column."""
    scale = alt.Scale(type="log") if log else alt.Scale()
    enc = {"x": alt.X(f"{x}:N", sort=None, title=None, axis=alt.Axis(labelAngle=0)),
           "y": alt.Y(f"{y}:Q", scale=scale, title=y_title or y, stack="zero" if stack else None),
           "tooltip": [c for c in df.columns]}
    if colour:
        enc["color"] = alt.Color(f"{colour}:N", sort=None, title=None,
                                 scale=alt.Scale(range=[BLUE, ORANGE, AQUA, YELLOW]))
        if not stack:
            enc["xOffset"] = alt.XOffset(f"{colour}:N", sort=None)
    mark = alt.Chart(df).mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3,
                                  color=BLUE)
    st.altair_chart(mark.encode(**enc).properties(height=height), width="stretch")


def table(rows, **kw):
    st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch", **kw)


def b64_image(b: str) -> bytes:
    return base64.b64decode(b)


# ====================================================================================== state
CANON = D.canon()
ENV = D.environment()
FB_INDEX = D.fallback_index()
LIVE_OK = P is not None and ENV["live_ok"]


@st.cache_resource(show_spinner="Loading the detector (ONNX, CPU)…")
def get_detector():
    return P.load_model()


@st.cache_data(show_spinner="Running the onboard chain on this image…", max_entries=24)
def compute(kind: str, key: str, data: bytes | None, labels: str | None, settings: tuple):
    """(bundle, artifacts) for one input and one group of settings. Raises with a screen message."""
    det, model_path = get_detector()
    s = P.Settings(*settings)
    if kind == "swath":
        img, info, _ = P.bundled_swath()
        source = {"kind": "sample", "label": "SYNTH", "synthetic": True, "key": SWATH_KEY,
                  "note": "9 bundled synthetic stand-in tiles (no Airbus pixels): the chain runs "
                          "end to end, the numbers are not measurements"}
    elif kind == "tile":
        path = D.QUICKSTART / "tiles" / key
        img, info = P.read_image(path.read_bytes(), key)
        source = {"kind": "sample", "label": "SYNTH", "synthetic": True, "key": Path(key).stem,
                  "note": "a bundled synthetic stand-in tile (no Airbus pixels)"}
    else:
        img, info = P.read_image(data, key)
        source = None
    gts = P.parse_labels(labels, info) if labels is not None else None
    return P.run_all(img, info, det, s, gts=gts, source=source, model_path=model_path)


# ====================================================================================== sidebar
with st.sidebar:
    st.header("Run mode")
    options = ["Live (CPU)", "Static fallback"]
    if not LIVE_OK:
        st.error("The live pipeline cannot run here, so the page is showing pre-generated results.")
        if LIVE_IMPORT_ERROR:
            st.caption(f"Import failed: {LIVE_IMPORT_ERROR}")
        for r in ENV["blocking"]:
            st.markdown(f"**Missing — {r['name']}** ({r['needed_for']})  \n{r['detail']}  \nFix: {r['fix']}")
        if LIVE_IMPORT_ERROR and not ENV["blocking"]:
            st.markdown("Fix: `python -m pip install -r demo/requirements-dashboard.txt`")
    run_mode = st.radio("Source of the numbers", options, index=0 if LIVE_OK else 1,
                        disabled=not LIVE_OK,
                        help="Live runs the detector and encoder now. Static fallback shows results "
                             "stored by demo/make_fallback_assets.py from a known-good run.")
    LIVE = LIVE_OK and run_mode == options[0]

    st.header("Settings")
    conf = st.slider("Onboard confidence cut", 0.05, 0.95, 0.25, 0.05, disabled=not LIVE,
                     help="0.25 is the operating cut every experiment in the repo uses.")
    window = st.select_slider("SAHI window (px)", [512, 640, 768, 1024], 768, disabled=not LIVE,
                              help="768 is the detector's native input (report 16).")
    overlap = st.slider("SAHI overlap", 0.0, 0.5, 0.20, 0.05, disabled=not LIVE)
    context = st.selectbox("Tile context", list(D.CONTEXTS), format_func=D.CONTEXTS.get,
                           disabled=not LIVE,
                           help="The classic pre-filter was tuned on Airbus tiles. On an unfamiliar "
                                "image it can call open sea 'cloud' and drop every detection; the "
                                "manual settings are for that case and are shown as manual.")
    capture_h = st.slider("Capture time (hours after the simulated epoch)", 0.0, 23.0, 2.0, 0.5,
                          disabled=not LIVE,
                          help="When the image is taken decides how long it waits for a contact. "
                               "Section F shows every hour of the day.")
    if not LIVE:
        st.caption("Settings are fixed in static fallback: the stored run used the defaults.")

    with st.expander("Environment check"):
        for r in ENV["rows"]:
            mark = "✅" if r["ok"] else "➖" if r["optional"] else "❌"
            st.markdown(f"{mark} **{r['name']}** — {r['detail']}"
                        + ("" if r["ok"] else f"  \n↳ needed for {r['needed_for']}. Fix: {r['fix']}"))
        st.caption("✅ present · ❌ missing and used by this page · ➖ absent, and only the full "
                   "dataset / GPU demo needs it")

SETTINGS = (float(conf), int(window), float(overlap), context, float(capture_h), True)

st.title("Semantic downlink for ship monitoring — live demo")
st.caption("IASTAM 6.0, Problem 7. A demonstration on a laptop CPU: not flight hardware, not a prototype.")

tabs = st.tabs(["A · Overview", "B · Image", "C · Detection", "D · Semantic packet",
                "E · Experiment", "F · Communication", "G · Results", "H · Export"])

# ====================================================================================== B. input
bundle, artifacts, input_error = None, {}, None


def section_input():
    global bundle, artifacts, input_error, LIVE
    st.subheader("B. Image input")
    fb_samples = FB_INDEX.get("samples", [])
    if LIVE:
        src = st.radio("Image", ["Bundled sample", "Upload"], horizontal=True)
    else:
        src = "Bundled sample"
        st.info("Static fallback: only the pre-generated samples are available. Uploads need the live pipeline.")
    data = name = labels = None
    kind, key = "swath", SWATH_KEY
    if src == "Bundled sample":
        if LIVE:
            tiles = sorted(p.name for p in (D.QUICKSTART / "tiles").glob("*.jpg"))
            choices = {SWATH_KEY: "3×3 synthetic swath, 2304 × 2304 px (shows SAHI against plain YOLO)"}
            choices.update({t: f"single tile — {t}" for t in tiles})
            if not tiles:
                st.error("No bundled tiles in demo/quickstart/tiles. Regenerate them with "
                         "`python demo/quickstart/make_synthetic_tiles.py`, or upload an image.")
                return
        else:
            choices = {s["key"]: s["title"] for s in fb_samples}
            if not choices:
                input_error = ("No static fallback assets: " + FB_INDEX.get("error", "none found")
                               + ". Create them on a working machine with `python demo/make_fallback_assets.py`.")
                st.error(input_error)
                return
        key = st.selectbox("Sample", list(choices), format_func=choices.get)
        kind = "swath" if key == SWATH_KEY else "tile"
        st.caption("The bundled samples are SYNTHETIC stand-ins: the Airbus competition rules forbid "
                   "redistributing the real tiles. They show that the chain runs; nothing computed "
                   "on them is a measurement.")
    else:
        up = st.file_uploader("Satellite image (JPEG, PNG, TIFF or BMP; 8-bit; up to "
                              f"{P.MAX_SIDE} px a side)", type=["jpg", "jpeg", "png", "tif", "tiff", "bmp"])
        gt = st.file_uploader("Optional ground truth (YOLO .txt: `0 cx cy w h`, normalised). "
                              "Without it no accuracy figure is shown.", type=["txt"])
        if up is None:
            input_error = "No image yet: upload one, or switch to a bundled sample."
            st.info(input_error)
            return
        kind, key, data = "upload", up.name, up.getvalue()
        if gt is not None:
            try:
                labels = gt.getvalue().decode("utf-8")
            except UnicodeDecodeError:
                st.error("The label file is not text (expected a YOLO .txt). It was ignored.")

    if LIVE:
        try:
            bundle, artifacts = compute(kind, key, data, labels, SETTINGS)
        except (ValueError, FileNotFoundError) as e:
            input_error = f"Image rejected: {e}" if kind == "upload" else str(e)
            st.error(input_error)
        except Exception as e:  # noqa: BLE001  the live run failed: say so, then fall back
            st.error(f"The live run failed: {type(e).__name__}: {e}")
            with st.expander("Technical details"):
                st.code(traceback.format_exc())
            LIVE = False
    if bundle is None and not LIVE:
        fb_key = Path(key).stem if kind == "tile" else key
        try:
            bundle, artifacts = D.load_fallback(fb_key)
            input_error = None
            st.warning(f"Showing STATIC results generated {bundle['meta']['generated_at']} at commit "
                       f"`{bundle['meta']['commit']}`. Nothing below was computed just now.")
            stale = D.fallback_staleness(FB_INDEX, CANON)
            if stale:
                st.warning("The committed results changed since these assets were generated "
                           "(the canonical numbers on this page are still read live): " + "; ".join(stale))
        except (FileNotFoundError, ValueError) as e:
            input_error = f"No static fallback for this input: {e}"
            st.error(input_error)
    if bundle is None:
        return

    i = bundle["input"]
    c1, c2 = st.columns([3, 2])
    with c1:
        st.image(artifacts["original.jpg"], caption=i["name"], width="stretch")
    with c2:
        m1, m2 = st.columns(2)
        m1.metric("Dimensions", f"{i['width']} × {i['height']} px")
        m2.metric("File size", fmt_bytes(i["file_bytes"]), help="As stored (compressed).")
        m1.metric("Raw size", fmt_bytes(i["raw_bytes"]),
                  help="H × W × 3 bytes, uncompressed 8-bit RGB: the B0 baseline every reduction is measured against.")
        m2.metric("Format", f"{i['format']}, {i['channels_in']} ch")
        for n in i["notes"]:
            st.caption(f"note: {n}")
        st.markdown(f"**Source:** {bundle['source']['label']} — {bundle['source']['note']}")
        gt_n = i["ground_truth"]
        st.markdown("**Ground truth:** " + (f"{gt_n['n']} labelled ships supplied" if gt_n else
                                            "none supplied, so no accuracy figure is computed for this image"))
        g = bundle["grid"]
        st.markdown(f"**Tile grid:** {g['rows']} × {g['cols']} tiles of 768 px; context from: {g['context_source']}")
        table([{"tile": f"r{t['row'] + 1} c{t['col'] + 1}", "pre-filter verdict": t["prefilter"],
                "policy context": t["context"]} for t in g["tiles"]], height=220)


with tabs[1]:
    guard(section_input)

HAVE = bundle is not None
SYNTH = HAVE and bundle["source"].get("synthetic", False)


def need_image() -> bool:
    if not HAVE:
        st.info(input_error or "No image loaded. Choose one in section B.")
    return HAVE


def image_label() -> str:
    return ("SYNTH: a synthetic stand-in image, not a measurement" if SYNTH else
            "this uploaded image only: one image is a spot check, not a benchmark")


# ====================================================================================== A. overview
def section_overview():
    st.subheader("A. The problem, and the idea")
    h = CANON.get("headline")
    if h:
        st.markdown(
            f"A small Earth-observation satellite images about **{h['MB_raw_per_day'] / 1e3:,.0f} GB** of ocean a "
            f"day and, on its share of one ground station's passes, can send down roughly "
            f"**{h['bent_pipe_MB_sent_per_day']:,.0f} MB**. A bent pipe therefore throws away more than 99% of "
            f"what it sees, and what does arrive is hours old.")
    st.markdown(
        "**Semantic downlink** sends *what the image means* instead of the image. The satellite finds "
        "the ships itself and spends the link on information about them: a confident detection "
        "costs a few dozen bytes; an uncertain one earns a small picture so the ground can check it; "
        "a coastline, where the detector is weakest, earns its context.")
    st.graphviz_chart("""
        digraph G { rankdir=LR; node [shape=box, style="rounded", fontname="Helvetica", fontsize=11];
          edge [fontname="Helvetica", fontsize=9];
          subgraph cluster_sat { label="ONBOARD (laptop CPU in this demo)"; style="rounded,dashed"; fontname="Helvetica";
            cam [label="Captured image\\n768 px tiles"];
            pre [label="Pre-filter\\ncloud / coast / sea"];
            det [label="YOLOv8n detector\\nplain, or SAHI + fusion"];
            pol [label="Semantic policy\\nP0 discard · P1 record\\nP2 + ROI · P3 + context"];
            enc [label="Packet encoder\\nrecords + JPEG crops\\nCCSDS packets"];
            sch [label="Value-greedy\\nscheduler"];
            cam -> pre -> det -> pol -> enc -> sch; }
          rel [label="Relay satellite\\n(B4, optional)"];
          gs  [label="Ground station\\ndecode + CRC check"];
          sch -> gs [label="direct pass"]; sch -> rel [label="inter-satellite link"]; rel -> gs [label="relay's pass"];
        }""")
    st.markdown("**What each priority level sends** (paper Table I):")
    table([{"level": "P0 — discard", "when": "below the onboard cut, or on a cloud tile", "what goes down": "nothing"},
           {"level": "P1 — metadata", "when": "confident detection", "what goes down": "one binary record: position, size, confidence, time"},
           {"level": "P2 — + ROI", "when": "uncertain detection", "what goes down": "the record + a tight JPEG crop of the ship"},
           {"level": "P3 — + context", "when": "detection on a coast", "what goes down": "the record + crop + the surrounding context image"}])

    st.subheader("Canonical results (read from code/results now)")
    if CANON["missing"]:
        st.error("Result files are missing, so some canonical numbers cannot be shown: "
                 + ", ".join(CANON["missing"]) + ". Restore them with `git checkout -- code/results`.")
    c = st.columns(4)
    det = {r["key"]: r for r in (CANON.get("detection") or {}).get("rows", [])}
    ss = CANON.get("steady_state")
    if h:
        c[0].metric("Data reduction, simulated day", f"{h['reduction_x']:,.0f}×", help=h["source"])
        c[0].caption(f"{h['label']}. {h['measured_share_percent']:.0f}% of the bytes sent are MEASURED "
                     f"(coastal tiles as real JPEGs); {h['modeled_share_percent']:.0f}% are MODELED "
                     f"(thumbnails and ship crops). An earlier all-modeled estimate was "
                     f"{h['earlier_all_modeled_x']:,.0f}×; it is not the headline.")
        band = h["cloud_band"]
        c[1].metric("Ship recall delivered", f"{h['ship_recall']:.3f}", help=h["source"])
        c[1].caption(f"{h['label']}, at an assumed 15% cloud. Band over 0–50% cloud: "
                     f"{band[0]:.2f}–{band[1]:.2f}. Never quoted without the cloud assumption.")
    if "B1" in det:
        c[2].metric("B1 → B2 recall", f"{det['B1']['recall']:.3f} → {det['B2']['recall']:.3f}")
        c[2].caption(f"REAL: plain YOLO on a whole scene, then SAHI, on the same {det['B1']['scope']}. "
                     f"Other recall figures in the repo belong to other configurations: see section C.")
    if ss:
        ours = ss["runs"]["share_0.25_Value-greedy (ours)"]["per_day"]
        r = [d["ship_recall"] for d in ours]
        c[3].metric("Six days over capacity", f"{min(r):.3f}–{max(r):.3f}")
        c[3].caption(f"{ss['label']}: recall on each of {ss['days']} consecutive days when a day offers "
                     f"more than the link share sustains. See section F.")
    s = CANON.get("sensitivity")
    if s:
        st.caption(f"Sensitivity ({s['label']}): the lead over the fair baseline holds in {s['holds']} of "
                   f"{s['of']} settings; every failure is at 160,000 tiles/day, where the margin is "
                   f"{s['lead_at_160k_pts']:.1f} points. Source: {s['source']}.")
    v = CANON.get("validation")
    if v:
        with st.expander("Validation status and stated gaps (wp29)"):
            for k, item in v.items():
                st.markdown(f"**{k}. {item['title']}** — {item['status']}")
                for lim in item["limits"]:
                    st.caption(lim)


# ====================================================================================== C. detection
def section_detection():
    st.subheader("C. Detection — plain YOLO against SAHI")
    if need_image():
        p = bundle["perception"]
        s = bundle["settings"]
        st.markdown(p["note"])
        cols = st.columns(2)
        for col, key, title, art in ((cols[0], "whole", "Plain YOLO — one call on the whole image", "detections_plain_yolo.jpg"),
                                     (cols[1], "sahi", "SAHI — overlapping windows + fusion", "detections_sahi.jpg")):
            b = p[key]
            with col:
                st.markdown(f"**{title}**")
                st.image(artifacts[art], width="stretch")
                m = st.columns(3)
                m[0].metric(f"Detections ≥ {s['conf']:g}", b["n_at_or_above_cut"])
                m[1].metric("Detector calls", b["calls"])
                m[2].metric("Time", fmt_time(b["seconds"]), help="Wall clock on this machine, CPU.")
                st.caption(f"{b['n_raw'] - b['n_at_or_above_cut']} more boxes below the cut (grey) are "
                           f"never transmitted. Counts are {image_label()}.")
                kept = [d for d in b["detections"] if d["at_or_above_cut"]]
                if kept:
                    table([{k: d[k] for k in ("class", "confidence", "cx", "cy", "w", "h")} for d in kept], height=210)
        if p["whole"]["quality"]:
            st.markdown("**Scored against the supplied ground truth** (IoU 0.5, at the onboard cut):")
            table([{"configuration": n, **{k: q[k] for k in ("n_gt", "TP", "FP", "FN", "precision", "recall", "F1", "AP50")}}
                   for n, q in (("plain YOLO", p["whole"]["quality"]), ("SAHI + fusion", p["sahi"]["quality"]))])
            st.caption("One image is a spot check, not a benchmark. The measured figures are below.")
        else:
            st.info("No ground truth for this image: the counts and confidences above are NOT accuracy. "
                    "Recall, precision and AP exist only for the labelled test data, below.")

    st.markdown("#### Which recall belongs to which configuration (committed results)")
    d = CANON.get("detection")
    if not d:
        st.error("code/results/wp26_b0_b4.json is missing, so the measured detection table cannot be shown.")
        return
    table([{"configuration": r["config"], "recall": r["recall"], "precision": r["precision"], "F1": r["F1"],
            "AP50": r["AP50"], "ships": r["n_gt"], "measured on": r["scope"], "source": r["source"]}
           for r in d["rows"]])
    by = {r["key"]: r for r in d["rows"]}
    st.markdown(
        f"- **B1 and B2 are defined on the same scenes** (wp26): one call on a whole "
        f"{by['B1']['scope'].split('(')[1].split(')')[0]} scene finds **{by['B1']['recall']:.3f}** of the ships; SAHI on "
        f"those scenes finds **{by['B2']['recall']:.3f}**, at {d['sahi_compute_x']:.2f}× the detector calls.\n"
        f"- The two *reference* rows are **not B1**. They run the detector at its native resolution on "
        f"each 768 px tile, which on a scene is already a slicing stage. Against that plain tiling SAHI "
        f"does not win on these stitched scenes ({by['B2']['recall']:.3f} vs {by['per_tile']['recall']:.3f}): no ship crosses a "
        f"seam between independently captured tiles.\n"
        f"- On this page, plain YOLO on an image that fits one 768 px window is the native-tile case; "
        f"on a larger image it is the B1 case.")
    df = pd.DataFrame([{"configuration": {"B1": "B1 plain YOLO", "B2": "B2 SAHI", "B3": "B3/B4 semantic",
                                          "per_tile": "ref: per-tile", "native": "ref: native tiles"}[r["key"]],
                        "recall": r["recall"], "what": "paper baseline" if r["is_paper_baseline"] else "reference (not B1)"}
                       for r in d["rows"]])
    bars(df, "configuration", "recall", colour="what", y_title="recall @ conf 0.25, IoU 0.5 [REAL]")


# ====================================================================================== D. packet
def section_packet():
    st.subheader("D. The semantic packet (B3 / B4 payload)")
    if not need_image():
        return
    m = bundle["modes"]["B3"]
    b = m["bytes"]
    c1, c2 = st.columns([3, 2])
    with c1:
        st.image(artifacts["semantic_levels.jpg"], width="stretch",
                 caption="Boxes coloured by level: P1 green, P2 yellow, P3 orange, P0 grey. Tile labels are the policy context.")
    with c2:
        st.markdown("**Level of every SAHI detection**")
        table([{"level": k, "detections": v} for k, v in m["level_histogram"].items()])
        st.markdown("**Serialized size** — the bytes of the real packet stream")
        k = st.columns(3)
        k[0].metric("Total", fmt_bytes(b["total"]))
        k[1].metric("Payload", fmt_bytes(b["payload"]), help="Semantic records + JPEG image data.")
        k[2].metric("Overhead", fmt_bytes(b["overhead"]),
                    help="Packet headers and CRC, image headers, JPEG headers.")
        if b["total"]:
            st.caption(f"Overhead is {100 * b['overhead'] / b['total']:.1f}% of the packet. Bytes are MEASURED "
                       f"(the length of the stream), on {image_label()}.")
    if not b["total"]:
        st.info("The packet is empty: no detection reached the onboard cut on a non-cloud tile, so "
                "nothing is transmitted for this image. That is the semantic policy working: a cloud "
                "tile costs zero bytes.")
        return
    p1, p2, p3 = st.columns(3)
    with p1:
        st.markdown("**Payload**")
        table([{"part": k, "bytes": v} for k, v in b["payload_parts"].items() if v])
    with p2:
        st.markdown("**Overhead**")
        table([{"part": k, "bytes": v} for k, v in b["overhead_parts"].items()])
    with p3:
        st.markdown("**By product**")
        table([{"product": k, **v} for k, v in b["by_kind"].items()])
    st.caption(f"On air, CCSDS TM framing with RS(255,223) would make this {fmt_bytes(b['on_air_with_TM_framing'])}. "
               f"That is reported only: the simulated link capacity already carries the coding overhead.")

    st.markdown("**Structured records, as decoded on the ground**")
    if m["records"]:
        table(m["records"], height=260)
        g = m["ground_decode"]
        st.caption(f"Ground decode of the byte stream: {g['records']} records, {g['rois']} ROI crops, "
                   f"{g['contexts']} context images; {g['crc']}.")
    if m["rois"]:
        st.markdown("**ROI crops (P2)** — the JPEG bytes that were in the packet")
        cols = st.columns(8)
        for n, r in enumerate(m["rois"][:16]):
            cols[n % 8].image(b64_image(r["jpeg_b64"]), caption=f"{r['w']}×{r['h']} px, {r['jpeg_bytes']} B")
        if len(m["rois"]) > 16:
            st.caption(f"{len(m['rois']) - 16} more crops are in the downloadable stream (section H).")
    if m["contexts"]:
        st.markdown("**Context images (P3)**")
        cols = st.columns(4)
        for n, r in enumerate(m["contexts"][:4]):
            cols[n % 4].image(b64_image(r["jpeg_b64"]),
                              caption=f"{r['w']}×{r['h']} px, quality {r['quality']}, {fmt_bytes(r['jpeg_bytes'])}")
    st.markdown("**Downlink order** — value per byte, highest first (value-greedy scheduler)")
    order = sorted(m["items"], key=lambda it: -(it["value"] / it["bytes"]))
    table([{"order": n + 1, "kind": it["kind"], "bytes": it["bytes"], "value": it["value"],
            "value per kB": round(1e3 * it["value"] / it["bytes"], 3),
            "truncatable to": f"{100 * it['min_fraction']:.0f}%" if it["progressive"] else "no"}
           for n, it in enumerate(order)], height=240)


# ====================================================================================== E. experiment
def section_experiment():
    st.subheader("E. Experiment — one pipeline, five configurations")
    st.markdown("B0 to B4 are one chain with three switches: what the detector sees, what goes on "
                "the downlink, and whether a relay may carry it. Each step adds one thing.")
    table([{"mode": k, "perception": v["perception"], "downlink payload": v["payload"],
            "relay": "allowed" if v["relay"] else "no", "what it adds": v["adds"]} for k, v in D.MODE_INFO.items()])
    st.radio("Configuration to inspect in sections F and G", list(D.MODES), index=3, horizontal=True,
             key="mode", format_func=lambda k: D.MODE_INFO[k]["title"])
    mode = st.session_state["mode"]
    st.info(D.MODE_INFO[mode]["adds"])
    st.radio("B4 route", list(D.ROUTES), index=list(D.ROUTES).index("policy"), horizontal=True, key="route",
             format_func=lambda k: {"policy": "Policy-chosen (default)", "direct": "Manual: direct only",
                                    "relay": "Manual: relay only"}[k],
             disabled=not D.MODE_INFO[mode]["relay"],
             help="Only B4 has a relay. 'Policy-chosen' lets each item take the path with the smaller "
                  "cost J; the two manual settings force one path.")
    if not D.MODE_INFO[mode]["relay"]:
        st.caption(f"{mode} has no relay: it always goes direct to the ground station.")
    if HAVE:
        m = bundle["modes"][mode]
        c = st.columns(4)
        c[0].metric("Detector calls", m["detector_calls"])
        c[1].metric("Detections transmitted", m["n_transmitted"])
        c[2].metric("Bytes on the downlink", fmt_bytes(m["bytes"]["total"]))
        c[3].metric("Schedulable items", m["n_items"])
        st.caption(f"Computed on {image_label()}.")


# ====================================================================================== F. comms
def section_comms():
    st.subheader("F. Communication simulation")
    st.caption("SIM. Nothing here is a real satellite connection: orbits are propagated (SGP4), "
               "contact windows are geometry, rates come from a link-budget model, powers are assumptions.")
    mode, route = st.session_state.get("mode", "B3"), st.session_state.get("route", "policy")
    if need_image():
        comms = bundle["comms"]
        if comms.get("error"):
            st.error(f"The link simulation could not run ({comms['error']}). It needs the `skyfield` and "
                     f"`sgp4` packages: `python -m pip install -r demo/requirements-dashboard.txt`. "
                     f"The rest of the page is unaffected.")
        else:
            r = D.route_for(mode, route)
            run = comms["runs"][mode][r]
            st.markdown(f"**{D.MODE_INFO[mode]['title']}**, image captured at **{comms['capture_utc']} UTC** "
                        f"({comms['capture_h']:g} h after the simulated epoch).")
            c = st.columns(4)
            c[0].metric("Route", {"direct": "Direct", "policy": "Policy-chosen", "relay": "Relay"}[r])
            c[0].caption(f"Chosen by: {run['chosen_by']}." + ("" if D.MODE_INFO[mode]["relay"] else
                                                               f" {mode} has no relay."))
            c[1].metric("Path taken", f"{run['direct_items']} direct · {run['relay_items']} relay",
                        help="Items of this image that went down each path.")
            c[2].metric("Transmission duration", fmt_time(run["tx_s_total"]),
                        help="Time the transmitters are keyed for this image's bytes, at the physical link rate.")
            done = run["delivered_items"] == run["items"] and run["items"]
            c[3].metric("Capture → all on ground", fmt_time(run["latency_last_s"]) if done else
                        "not delivered" if run["items"] else "nothing to send",
                        help="Wait for the contact window(s) plus transmission.")
            if run["undelivered_items"]:
                st.warning(f"{run['undelivered_items']} of {run['items']} items were not delivered within the "
                           f"{comms['plan']['horizon_h']:g} h plan on this route (too large for the "
                           f"remaining pass capacity, or no window left).")
            elif not run["items"]:
                st.info("Nothing to send: this configuration produced no bytes for this image.")
            tx = run["tx_s"]
            st.caption("Transmit time by link — ground: " + fmt_time(tx["ground"]) + "; inter-satellite: "
                       + fmt_time(tx["isl"]) + "; relay's ground pass: " + fmt_time(tx["relay_ground"])
                       + ". The wait for a pass, not the transmission, is nearly all of the latency.")
            if run["deliveries"]:
                with st.expander(f"Every delivered item ({len(run['deliveries'])})"):
                    table(run["deliveries"], height=260)
            sw = comms.get("sweep")
            if sw:
                st.markdown("**Does the relay help? It depends on when the image is taken.** " + sw["what"] + ":")
                rows = [{"capture hour": x["capture_h"], "route": name, "hours": x[k]}
                        for x in sw["rows"] for k, name in (("direct_h", "direct only"), ("policy_h", "policy-chosen (may relay)"))
                        if x[k] is not None]
                df = pd.DataFrame(rows)
                st.altair_chart(alt.Chart(df).mark_line(point=alt.OverlayMarkDef(size=60), strokeWidth=2).encode(
                    x=alt.X("capture hour:Q", title="capture time (h after epoch)"),
                    y=alt.Y("hours:Q", title="capture → all on ground (h) [SIM]"),
                    color=alt.Color("route:N", title=None, scale=alt.Scale(range=[BLUE, ORANGE])),
                    tooltip=list(df.columns)).properties(height=260), width="stretch")
                med = df.groupby("route")["hours"].median()
                st.caption("Median over the 24 capture hours — " + "; ".join(f"{k}: {v:.2f} h" for k, v in med.items())
                           + ". One image on an otherwise empty link: no queue, no contention.")
            with st.expander("Link assumptions"):
                table([{"assumption": k, "value": str(v)} for k, v in comms["plan"]["assumptions"].items()])
                st.caption(comms["plan"]["assumption_label"])
            with st.expander("Contact plan (36 h)"):
                st.markdown("Primary satellite → ground station")
                table(comms["plan"]["primary_passes"])
                st.markdown("Relay satellite → ground station")
                table(comms["plan"]["relay_passes"])
                st.caption(f"{len(comms['plan']['isl_windows'])} inter-satellite windows in the same 36 h.")

    st.markdown("#### One image always fits. A whole day does not.")
    ss, h = CANON.get("steady_state"), CANON.get("headline")
    if not ss or not h:
        st.error("code/results/wp29_validation.json is missing, so the multi-day result cannot be shown.")
        return
    ours, fifo = ss["runs"]["share_0.25_Value-greedy (ours)"], ss["runs"]["share_0.25_FIFO"]
    rr = [d["ship_recall"] for d in ours["per_day"]]
    st.warning(
        f"A single image is a few kilobytes on an empty link, so it always completes. That is **not** "
        f"true of a nominal day: {ss['tiles_per_day']:,} tiles produce about **{h['MB_sent_per_day']:.0f} MB**, "
        f"and the link share sustains **{ours['sustained_capacity_MB_per_24h']} MB per 24 h** — the day offers "
        f"{100 * ours['offered_over_sustained']:.0f}% of capacity. The headline day is simulated alone with 36 h of "
        f"passes to drain it. Run {ss['days']} days back to back and the backlog is real:")
    c = st.columns(3)
    c[0].metric("Our scheduler: recall, every day", f"{min(rr):.3f}–{max(rr):.3f}")
    c[1].metric("Our scheduler: median latency",
                f"{min(d['latency_med_h'] for d in ours['per_day']):.1f}–{max(d['latency_med_h'] for d in ours['per_day']):.1f} h")
    c[2].metric("FIFO: median latency, day 1 → 6",
                f"{fifo['per_day'][0]['latency_med_h']:.1f} → {fifo['per_day'][-1]['latency_med_h']:.1f} h")
    df = pd.DataFrame([{"day": f"day {d['day']}", "policy": name, "median latency (h)": d["latency_med_h"],
                        "ship recall": d["ship_recall"]}
                       for name, run in (("value-greedy (ours)", ours), ("FIFO", fifo)) for d in run["per_day"]])
    g1, g2 = st.columns(2)
    with g1:
        bars(df, "day", "median latency (h)", colour="policy", y_title=f"median latency (h) [{ss['label']}]")
    with g2:
        bars(df, "day", "ship recall", colour="policy", y_title=f"ship recall [{ss['label']}]")
    st.caption(f"{ss['label']}, {ss['source']}. The value-greedy scheduler sheds bytes, not ships; FIFO falls "
               f"further behind each day and delivers {fifo['per_day'][-1]['ship_recall']:.3f} of day six's ships. One "
               f"assumption sits under the flat recall: a progressively truncated image counts as delivered "
               f"once it clears its minimum decodable fraction.")


# ====================================================================================== G. results
def section_results():
    st.subheader("G. Results")
    mode, route = st.session_state.get("mode", "B3"), st.session_state.get("route", "policy")
    if need_image():
        lab = bundle["labels"]
        s = D.mode_summary(bundle, mode, route)
        st.markdown(f"**{D.MODE_INFO[mode]['title']}** on this image — {image_label()}.")
        c = st.columns(4)
        c[0].metric("Raw size", fmt_bytes(s["bytes_raw"]))
        c[1].metric("Transmitted", fmt_bytes(s["bytes_tx"]))
        c[2].metric("Data reduction, this image", f"{s['reduction_percent']:.3f}%",
                    help="100 × (1 − transmitted / raw). B0 is slightly negative: packet headers are added to the raw pixels.")
        c[3].metric("Detections transmitted", s["detections_transmitted"])
        c = st.columns(4)
        c[0].metric("Processing", fmt_time(s["T_processing_s"]), help=lab["times"])
        c[1].metric("Encoding + decoding", fmt_time(s["T_encoding_s"] + (s["T_decoding_s"] or 0.0)), help=lab["times"])
        c[2].metric("Communication", fmt_time(s["T_communication_s"]), help=lab["link"])
        c[3].metric("Total latency", fmt_time(s["T_total_s"]),
                    help="T_processing + T_encoding + T_communication + T_decoding, added in sequence.")
        c = st.columns(4)
        c[0].metric("Processing energy", fmt_energy(s["E_processing_J"]),
                    help=f"ESTIMATE: {bundle['assumptions']['p_cpu_W']:g} W assumed × time measured on this machine.")
        c[1].metric("Communication energy", fmt_energy(s["E_communication_J"]),
                    help=f"ESTIMATE: {bundle['assumptions']['p_tx_W']:g} W ground / {bundle['assumptions']['p_isl_W']:g} W "
                         f"inter-satellite, assumed × simulated transmit time.")
        c[2].metric("Total energy", fmt_energy(s["E_total_J"]))
        share = bundle["modes"][mode]["transmitted_share_of_onboard"]
        q = bundle["modes"][mode]["quality"]
        if q:
            c[3].metric("Ships reported / ground truth", f"{q['recall']:.3f}",
                        help="Recall of the transmitted records against the supplied labels (IoU 0.5).")
        else:
            c[3].metric("Onboard detections transmitted", "—" if share is None else f"{100 * share:.0f}%",
                        help="Share of what the detector found at or above the cut that is sent. NOT accuracy: "
                             "without ground truth, information preservation against reality cannot be stated.")
        st.caption(f"Bytes: {lab['bytes']}. Times: {lab['times']}. Link: {lab['link']}. Energy: {lab['energy']} "
                   f"({bundle['assumptions']['label']}). Accuracy: {lab['accuracy']}.")
        if s["T_decoding_s"] is None:
            st.caption("B0 decoding is " + bundle["modes"][mode]["timing_s"]["decoding_note"] + ".")

        allm = [D.mode_summary(bundle, m, route) for m in D.MODES]
        st.markdown("**All five configurations, this image**")
        table([{"mode": x["mode"], "route": x["route"], "transmitted (B)": x["bytes_tx"],
                "reduction (%)": round(x["reduction_percent"], 4), "detector calls": x["detector_calls"],
                "detections sent": x["detections_transmitted"],
                "processing (s)": round(x["T_processing_s"], 4), "encoding (s)": round(x["T_encoding_s"], 5),
                "communication (h)": None if x["T_communication_s"] is None else round(x["T_communication_s"] / 3600, 3),
                "E processing (J)": round(x["E_processing_J"], 3),
                "E communication (J)": None if x["E_communication_J"] is None else round(x["E_communication_J"], 4),
                "E total (J)": None if x["E_total_J"] is None else round(x["E_total_J"], 3)} for x in allm])
        g1, g2 = st.columns(2)
        with g1:
            st.markdown("**Data volume** (log scale)")
            df = pd.DataFrame([{"mode": "raw image", "bytes": s["bytes_raw"]}]
                              + [{"mode": x["mode"], "bytes": x["bytes_tx"]} for x in allm if x["bytes_tx"]])
            bars(df, "mode", "bytes", log=True, y_title="bytes [MEASURED]")
            st.markdown("**Latency: onboard and ground stages**")
            df = pd.DataFrame([{"mode": x["mode"], "stage": k, "seconds": v} for x in allm
                               for k, v in (("processing", x["T_processing_s"]), ("encoding", x["T_encoding_s"]),
                                            ("decoding", x["T_decoding_s"] or 0.0))])
            bars(df, "mode", "seconds", colour="stage", stack=True, y_title="seconds [MEASURED, this machine]")
        with g2:
            st.markdown("**Energy**")
            df = pd.DataFrame([{"mode": x["mode"], "part": k, "joules": v} for x in allm
                               for k, v in (("processing", x["E_processing_J"]), ("communication", x["E_communication_J"]))
                               if v is not None])
            bars(df, "mode", "joules", colour="part", stack=True, y_title="joules [ESTIMATE]")
            st.markdown("**Latency: communication**")
            df = pd.DataFrame([{"mode": x["mode"], "hours": x["T_communication_s"] / 3600} for x in allm
                               if x["T_communication_s"] is not None])
            if len(df):
                bars(df, "mode", "hours", y_title="capture → all on ground (h) [SIM]")
            else:
                st.info("No communication figures: the link simulation did not run.")
        st.caption("Communication is hours and the other stages are milliseconds, so they are drawn on "
                   "separate charts rather than one misleading axis. B0's processing bar is the time to "
                   "packetize the raw pixels.")
        if any(x["quality"] for x in bundle["modes"].values()):
            st.markdown("**Detection quality on this image** (against the supplied labels)")
            df = pd.DataFrame([{"mode": k, "metric": n, "value": v["quality"][n]} for k, v in bundle["modes"].items()
                               if v["quality"] for n in ("precision", "recall", "F1") if v["quality"][n] is not None])
            bars(df, "mode", "value", colour="metric", y_title="score [REAL, one image]")

    st.markdown("#### The measured results (committed, not this image)")
    h, camp, det, en = CANON.get("headline"), CANON.get("campaign"), CANON.get("detection"), CANON.get("energy")
    if h:
        st.markdown(
            f"**Data reduction, simulated day: {h['reduction_x']:,.0f}× ({h['reduction_percent']:.2f}%)** — "
            f"{h['MB_raw_per_day']:,.0f} MB raw → {h['MB_sent_per_day']:.1f} MB sent [{h['label']}].  \n"
            f"MEASURED, {h['measured_share_percent']:.1f}% of the bytes: {h['measured']}.  \n"
            f"MODELED, {h['modeled_share_percent']:.1f}% of the bytes: {h['modeled']}.  \n"
            f"Source: {h['source']}.")
    if camp and det:
        rec = {r["key"]: r for r in det["rows"]}
        rows = []
        for m in D.MODES:
            d = camp["day"][m]
            q = rec.get("B3" if m == "B4" else m, {})
            rows.append({"mode": m, "detection recall, same scenes [REAL]": q.get("recall"),
                         "mean bytes per scene [REAL]": round(camp["mean_bytes_per_scene"][m]),
                         "delivered ship recall, day [SIM-over-REAL]": d["ship_recall"],
                         "MB sent / offered, day": f"{d['MB_sent']:.1f} / {d['MB_offered']:.1f}",
                         "median latency, day (h) [SIM]": d["latency_med_h"]})
        table(rows)
        st.caption(f"{camp['source']}: {camp['label']}. B0's delivered recall is what fits through the link, "
                   f"not what a detector finds. Detection recall and delivered recall are different inputs "
                   f"and are not steps of one curve.")
        g1, g2 = st.columns(2)
        with g1:
            bars(pd.DataFrame([{"mode": r["mode"], "recall": r["delivered ship recall, day [SIM-over-REAL]"]} for r in rows]),
                 "mode", "recall", y_title="delivered ship recall, one day [SIM-over-REAL]")
        with g2:
            bars(pd.DataFrame([{"mode": r["mode"], "hours": r["median latency, day (h) [SIM]"]} for r in rows]),
                 "mode", "hours", y_title="median latency, one day (h) [SIM]")
    if en:
        st.markdown("**Energy per day** — every figure an ESTIMATE; no power was measured")
        rows = [{"pipeline": "default: " + en["default"]["what"], **{k: en["default"][k] for k in
                 ("E_proc_kJ_day", "E_comm_kJ_day", "E_total_kJ_day", "proc_to_comm", "ES_proc")}}]
        if en["sahi_variant"]:
            v = en["sahi_variant"]
            rows.append({"pipeline": f"SAHI variant: {v['calls_per_tile']} detector calls per tile (labelled variant, not the default)",
                         **{k: v[k] for k in ("E_proc_kJ_day", "E_comm_kJ_day", "E_total_kJ_day", "proc_to_comm", "ES_proc")}})
        table(rows)
        df = pd.DataFrame([{"pipeline": n, "part": p, "kJ per day": r[k]} for n, r in zip(("default", "SAHI variant"), rows)
                           for p, k in (("processing", "E_proc_kJ_day"), ("communication", "E_comm_kJ_day"))])
        bars(df, "pipeline", "kJ per day", colour="part", stack=True, y_title="kJ per day [ESTIMATE]", height=240)
        st.caption(f"{en['label']}. Source: {en['source']}. Powers assumed: {en['powers_W']}. A bent pipe sending "
                   f"all raw data would need {en['bent_pipe_days_of_contact_needed']} days of contact per day; "
                   f"limited to the real contact time it spends about {en['bent_pipe_link_limited_kJ_day']} kJ/day, "
                   f"less than this pipeline, to deliver a fraction of a percent of the ships.")


# ====================================================================================== H. export
def section_export():
    st.subheader("H. Export")
    if not need_image():
        return
    route = st.session_state.get("route", "policy")
    stem = Path(bundle["input"]["name"]).stem
    st.caption(f"Everything below describes {image_label()}. Generated {bundle['meta']['generated_at']}, commit "
               f"`{bundle['meta']['commit']}`, {bundle['meta']['backend']}, model {bundle['meta']['model']}.")
    c = st.columns(3)
    c[0].download_button("Results (JSON)", json.dumps(D.slim(bundle), indent=2), f"{stem}_results.json", "application/json")
    c[0].download_button("Metrics, all modes (CSV)", D.metrics_csv(bundle, route), f"{stem}_metrics.csv", "text/csv")
    c[1].download_button("Detections (CSV)", D.detections_csv(bundle), f"{stem}_detections.csv", "text/csv")
    c[1].download_button("Semantic records (CSV)", D.records_csv(bundle), f"{stem}_records.csv", "text/csv",
                         disabled=not any(m["records"] for m in bundle["modes"].values()))
    c[2].download_button("Canonical results (JSON)", json.dumps({k: v for k, v in CANON.items() if k != "ledger"}, indent=2),
                         "canonical_results.json", "application/json")
    if artifacts.get("downlink_B3.bin"):
        c[2].download_button("B3 downlink stream (binary)", artifacts["downlink_B3.bin"], f"{stem}_downlink_B3.bin",
                             "application/octet-stream")
    st.markdown("**Detection visualisations**")
    c = st.columns(3)
    for col, (name, title) in zip(c, (("detections_plain_yolo.jpg", "Plain YOLO"), ("detections_sahi.jpg", "SAHI + fusion"),
                                      ("semantic_levels.jpg", "Semantic levels"))):
        col.image(artifacts[name], caption=title, width="stretch")
        col.download_button(f"Download — {title}", artifacts[name], f"{stem}_{name}", "image/jpeg")


for tab, fn in zip(tabs, (section_overview, None, section_detection, section_packet, section_experiment,
                          section_comms, section_results, section_export)):
    if fn is not None:
        with tab:
            guard(fn)
